from PyQt5 import QtCore, QtGui, QtWidgets
from models import Pinjam, session

class Form_Pinjam(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(424, 299)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 40, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 100, 101, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 100, 160, 84))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formPeminj = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.formPeminj.setObjectName("formPeminj")
        self.verticalLayout_2.addWidget(self.formPeminj)
        self.formBarang = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.formBarang.setObjectName("formBarang")
        self.verticalLayout_2.addWidget(self.formBarang)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_2.addWidget(self.dateEdit)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(110, 220, 80, 23))
        self.submit.clicked.connect(self.save)
        self.submit.setObjectName("submit")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(230, 220, 80, 23))
        self.reset.clicked.connect(self.clear)
        self.reset.setObjectName("reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "peminjaman alpha 0.1"))
        self.label.setText(_translate("MainWindow", "Form Peminjaman"))
        self.label_2.setText(_translate("MainWindow", "Peminjam :"))
        self.label_4.setText(_translate("MainWindow", "Nama Barang :"))
        self.label_3.setText(_translate("MainWindow", "Tanggal: "))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.reset.setText(_translate("MainWindow", "Reset"))

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def save(self):
        try:
            peminjam = self.formPeminj.text()
            barang = self.formBarang.text()
            tgl = self.dateEdit.date().toPyDate()
            peminjaman = Pinjam(nama=peminjam, barang=barang, tanggal=tgl, tipe="Pinjam")
            session.add(peminjaman)
            session.commit()
            self.messagebox("SUKSES", "Data Berhasil Disimpan")
            # QtWidgets.qApp.quit()
        except:
            self.messagebox("GAGAL", "Data Gagal Disimpan")
    
    def clear(self):
        self.formPeminj.clear()
        self.formBarang.clear()
